
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Darwin - 23.5.0 - arm64
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: /usr/bin/cc 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.out"
      
      The C compiler identification is AppleClang, found in:
        /Users/aa/Documents/PlatformIO/Projects/SmartSole/tools/anim/CMakeFiles/4.0.3/CompilerIdC/a.out
      
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineCompilerId.cmake:290 (message)"
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Detecting C compiler apple sysroot: "/usr/bin/cc" "-E" "apple-sdk.c"
        # 1 "apple-sdk.c"
        # 1 "<built-in>" 1
        # 1 "<built-in>" 3
        # 424 "<built-in>" 3
        # 1 "<command line>" 1
        # 1 "<built-in>" 2
        # 1 "apple-sdk.c" 2
        # 1 "/Library/Developer/CommandLineTools/SDKs/MacOSX14.5.sdk/usr/include/AvailabilityMacros.h" 1 3 4
        # 86 "/Library/Developer/CommandLineTools/SDKs/MacOSX14.5.sdk/usr/include/AvailabilityMacros.h" 3 4
        # 1 "/Library/Developer/CommandLineTools/SDKs/MacOSX14.5.sdk/usr/include/AvailabilityVersions.h" 1 3 4
        # 87 "/Library/Developer/CommandLineTools/SDKs/MacOSX14.5.sdk/usr/include/AvailabilityMacros.h" 2 3 4
        # 206 "/Library/Developer/CommandLineTools/SDKs/MacOSX14.5.sdk/usr/include/AvailabilityMacros.h" 3 4
        # 1 "/Library/Developer/CommandLineTools/SDKs/MacOSX14.5.sdk/usr/include/Availability.h" 1 3 4
        # 177 "/Library/Developer/CommandLineTools/SDKs/MacOSX14.5.sdk/usr/include/Availability.h" 3 4
        # 1 "/Library/Developer/CommandLineTools/SDKs/MacOSX14.5.sdk/usr/include/AvailabilityInternal.h" 1 3 4
        # 176 "/Library/Developer/CommandLineTools/SDKs/MacOSX14.5.sdk/usr/include/AvailabilityInternal.h" 3 4
        # 1 "/Library/Developer/CommandLineTools/SDKs/MacOSX14.5.sdk/usr/include/AvailabilityInternalLegacy.h" 1 3 4
        # 177 "/Library/Developer/CommandLineTools/SDKs/MacOSX14.5.sdk/usr/include/AvailabilityInternal.h" 2 3 4
        # 178 "/Library/Developer/CommandLineTools/SDKs/MacOSX14.5.sdk/usr/include/Availability.h" 2 3 4
        # 207 "/Library/Developer/CommandLineTools/SDKs/MacOSX14.5.sdk/usr/include/AvailabilityMacros.h" 2 3 4
        # 2 "apple-sdk.c" 2
        
        
      Found apple sysroot: /Library/Developer/CommandLineTools/SDKs/MacOSX14.5.sdk
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: /usr/bin/c++ 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "a.out"
      
      The CXX compiler identification is AppleClang, found in:
        /Users/aa/Documents/PlatformIO/Projects/SmartSole/tools/anim/CMakeFiles/4.0.3/CompilerIdCXX/a.out
      
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineCompilerId.cmake:290 (message)"
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Detecting CXX compiler apple sysroot: "/usr/bin/c++" "-E" "apple-sdk.cpp"
        # 1 "apple-sdk.cpp"
        # 1 "<built-in>" 1
        # 1 "<built-in>" 3
        # 439 "<built-in>" 3
        # 1 "<command line>" 1
        # 1 "<built-in>" 2
        # 1 "apple-sdk.cpp" 2
        # 1 "/Library/Developer/CommandLineTools/SDKs/MacOSX14.5.sdk/usr/include/AvailabilityMacros.h" 1 3 4
        # 86 "/Library/Developer/CommandLineTools/SDKs/MacOSX14.5.sdk/usr/include/AvailabilityMacros.h" 3 4
        # 1 "/Library/Developer/CommandLineTools/SDKs/MacOSX14.5.sdk/usr/include/AvailabilityVersions.h" 1 3 4
        # 87 "/Library/Developer/CommandLineTools/SDKs/MacOSX14.5.sdk/usr/include/AvailabilityMacros.h" 2 3 4
        # 206 "/Library/Developer/CommandLineTools/SDKs/MacOSX14.5.sdk/usr/include/AvailabilityMacros.h" 3 4
        # 1 "/Library/Developer/CommandLineTools/SDKs/MacOSX14.5.sdk/usr/include/Availability.h" 1 3 4
        # 177 "/Library/Developer/CommandLineTools/SDKs/MacOSX14.5.sdk/usr/include/Availability.h" 3 4
        # 1 "/Library/Developer/CommandLineTools/SDKs/MacOSX14.5.sdk/usr/include/AvailabilityInternal.h" 1 3 4
        # 176 "/Library/Developer/CommandLineTools/SDKs/MacOSX14.5.sdk/usr/include/AvailabilityInternal.h" 3 4
        # 1 "/Library/Developer/CommandLineTools/SDKs/MacOSX14.5.sdk/usr/include/AvailabilityInternalLegacy.h" 1 3 4
        # 177 "/Library/Developer/CommandLineTools/SDKs/MacOSX14.5.sdk/usr/include/AvailabilityInternal.h" 2 3 4
        # 178 "/Library/Developer/CommandLineTools/SDKs/MacOSX14.5.sdk/usr/include/Availability.h" 2 3 4
        # 207 "/Library/Developer/CommandLineTools/SDKs/MacOSX14.5.sdk/usr/include/AvailabilityMacros.h" 2 3 4
        # 2 "apple-sdk.cpp" 2
        
        
      Found apple sysroot: /Library/Developer/CommandLineTools/SDKs/MacOSX14.5.sdk
